// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0aMyjo-GbgLaC8QtJZcMLXqbsTnHbuqg',
    appId: '1:496422631569:web:d00dd6cf1fad1cb333e730',
    messagingSenderId: '496422631569',
    projectId: 'grownest-f4141',
    authDomain: 'grownest-f4141.firebaseapp.com',
    storageBucket: 'grownest-f4141.firebasestorage.app',
    measurementId: 'G-5JZX3DQDV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClz6tsLP_snHPhd-HdZfyMSxhMqwliwvM',
    appId: '1:496422631569:android:4c2b1a295766193933e730',
    messagingSenderId: '496422631569',
    projectId: 'grownest-f4141',
    storageBucket: 'grownest-f4141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4rE63XJjlhXM5t0hM69SILB92e_-S93g',
    appId: '1:496422631569:ios:fb3e9d1c01da56f833e730',
    messagingSenderId: '496422631569',
    projectId: 'grownest-f4141',
    storageBucket: 'grownest-f4141.firebasestorage.app',
    androidClientId:
        '496422631569-lvkjkoacb96du2me574mur2gs6vpsadi.apps.googleusercontent.com',
    iosClientId:
        '496422631569-ag1k5kfr2g2h4la005u4ro6kuau4ke9j.apps.googleusercontent.com',
    iosBundleId: 'com.miniadimlar.app',
  );
}
